//
// Generated file, do not edit! Created by nedtool 4.6 from src/node/communication/routing/aodvTestRouting/AodvTestRoutingDataPacket.msg.
//

#ifndef _AODVTESTROUTINGDATAPACKET_M_H_
#define _AODVTESTROUTINGDATAPACKET_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
 
#include "RoutingPacket_m.h"
// }}

/**
 * Class generated from <tt>src/node/communication/routing/aodvTestRouting/AodvTestRoutingDataPacket.msg:29</tt> by nedtool.
 * <pre>
 * packet PacketDATA extends RoutingPacket
 * {
 *     string destinationAodv;
 * }
 * </pre>
 */
class PacketDATA : public ::RoutingPacket
{
  protected:
    opp_string destinationAodv_var;

  private:
    void copy(const PacketDATA& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const PacketDATA&);

  public:
    PacketDATA(const char *name=NULL, int kind=0);
    PacketDATA(const PacketDATA& other);
    virtual ~PacketDATA();
    PacketDATA& operator=(const PacketDATA& other);
    virtual PacketDATA *dup() const {return new PacketDATA(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getDestinationAodv() const;
    virtual void setDestinationAodv(const char * destinationAodv);
};

inline void doPacking(cCommBuffer *b, PacketDATA& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, PacketDATA& obj) {obj.parsimUnpack(b);}


#endif // ifndef _AODVTESTROUTINGDATAPACKET_M_H_

