//
// Generated file, do not edit! Created by nedtool 4.6 from src/node/application/geoSync/GeoSyncPacketType.msg.
//

#ifndef _GEOSYNCPACKETTYPE_M_H_
#define _GEOSYNCPACKETTYPE_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "ApplicationPacket_m.h"
// }}

/**
 * Class generated from <tt>src/node/application/geoSync/GeoSyncPacketType.msg:20</tt> by nedtool.
 * <pre>
 * packet GeoSyncPacketType extends ApplicationPacket
 * {
 *     int type;
 * }
 * </pre>
 */
class GeoSyncPacketType : public ::ApplicationPacket
{
  protected:
    int type_var;

  private:
    void copy(const GeoSyncPacketType& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const GeoSyncPacketType&);

  public:
    GeoSyncPacketType(const char *name=NULL, int kind=0);
    GeoSyncPacketType(const GeoSyncPacketType& other);
    virtual ~GeoSyncPacketType();
    GeoSyncPacketType& operator=(const GeoSyncPacketType& other);
    virtual GeoSyncPacketType *dup() const {return new GeoSyncPacketType(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getType() const;
    virtual void setType(int type);
};

inline void doPacking(cCommBuffer *b, GeoSyncPacketType& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, GeoSyncPacketType& obj) {obj.parsimUnpack(b);}


#endif // ifndef _GEOSYNCPACKETTYPE_M_H_

