//
// Generated file, do not edit! Created by nedtool 4.6 from src/node/application/geoSync/HECOPSPacket.msg.
//

#ifndef _HECOPSPACKET_M_H_
#define _HECOPSPACKET_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "GeoSyncPacketType_m.h"
// }}

/**
 * Class generated from <tt>src/node/application/geoSync/HECOPSPacket.msg:22</tt> by nedtool.
 * <pre>
 * packet HECOPSPacket extends GeoSyncPacketType
 * {
 *     int someField;
 * }
 * </pre>
 */
class HECOPSPacket : public ::GeoSyncPacketType
{
  protected:
    int someField_var;

  private:
    void copy(const HECOPSPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const HECOPSPacket&);

  public:
    HECOPSPacket(const char *name=NULL, int kind=0);
    HECOPSPacket(const HECOPSPacket& other);
    virtual ~HECOPSPacket();
    HECOPSPacket& operator=(const HECOPSPacket& other);
    virtual HECOPSPacket *dup() const {return new HECOPSPacket(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getSomeField() const;
    virtual void setSomeField(int someField);
};

inline void doPacking(cCommBuffer *b, HECOPSPacket& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, HECOPSPacket& obj) {obj.parsimUnpack(b);}


#endif // ifndef _HECOPSPACKET_M_H_

