#!/bin/bash

if [ $# -ne 1 ]; then
    echo "ERROR! Usage: $0 [LISHA|SSB|TWIST]"
    exit 1
fi

if [ "$1" == "LISHA" ]; then
    FILE="../Parameters/nodeMap/LISHA.ini"
elif [ "$1" == "SSB" ]; then
    FILE="../Parameters/nodeMap/SSB.ini"
    echo "include ../Parameters/nodeMap/SSB.ini" > office_deployment.ini
elif [ "$1" == "TWIST" ]; then
    FILE="../Parameters/nodeMap/TWIST.ini"
else
    echo "ERROR! Usage: $0 [LISHA|SSB|TWIST]"
    exit 1
fi

echo "# Generated by $0" > office_deployment.ini
echo "include $FILE" >> office_deployment.ini
NODES=$(grep 'SN.node\[' "$FILE" | grep "Coor" | sed 's:SN.node\[\([0-9][0-9]*\)\].*:\1:g' | sort -n | tail -1)
NODES=$((NODES+1))
python3 ./office_deployment.py $NODES >> office_deployment.ini
